[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "Scriptorium"
version = "0.1.0"
description = "Scriptorium API"
authors = [
  { name = "Grigorii Feoktistov" },
]
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "Framework :: FastAPI",
]
dependencies = [
    "passlib==1.7.4",
    "bcrypt==3.2.0",
    "annotated-doc",
    "annotated-types",
    "anyio",
    "asyncpg",
    "click",
    "dnspython",
    "email-validator",
    "fastapi",
    "h11",
    "idna",
    "psycopg2",
    "pydantic",
    "pydantic-settings",
    "pydantic_core",
    "python-dotenv",
    "sniffio",
    "SQLAlchemy[asyncio]",
    "sqlmodel",
    "starlette",
    "typing-inspection",
    "typing_extensions",
    "uvicorn",
    "python-jose[cryptography]",
    "python-multipart",
    "python-magic",
    "libmagic",
    "aiobotocore"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["app*"]